name: Compilar mi APK

on:
  push:
    branches: [ "main", "master" ] # Se activa cada vez que guardas cambios

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Dar permisos a Gradle
      run: chmod +x ./gradlew

    - name: Compilar APK de Depuración (Debug)
      run: ./gradlew assembleDebug

    - name: Subir el archivo APK resultante
      uses: actions/upload-artifact@v4
      with:
        name: RelojDespertador-APK
        path: app/build/outputs/apk/debug/app-debug.apk
